version: 2

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - gosec
    - gocyclo
    - dupl
    - goconst

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gosec:
    excludes:
      - G104 # Unhandled errors
      - G107 # URL provided to HTTP request as taint input
      - G402 # TLS InsecureSkipVerify set true

output:
  formats:
    - colored-line-number  # updated from deprecated 'format'
  print-issued-lines: true
  print-linter-name: true