version: "1"

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - gosec
    - gocyclo
    - dupl
    - goconst
    - goimports

run:
  timeout: 5m
  tests: true 